# Generated by Django 6.0.5 on 2026-06-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("token_hash", models.CharField(editable=False, max_length=128, unique=True)),
                ("prefijo", models.CharField(blank=True, editable=False, max_length=24)),
                ("activo", models.BooleanField(default=True)),
                ("ultimo_uso_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "token de dispositivo",
                "verbose_name_plural": "tokens de dispositivo",
                "ordering": ["nombre"],
            },
        ),
    ]
