# Generated by Codex on 2026-06-02

import decimal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanalCobro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("metodo_pago", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="canales_cobro", to="ledger.metodopago")),
            ],
            options={
                "verbose_name": "canal de cobro",
                "verbose_name_plural": "canales de cobro",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EsquemaComision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("porcentaje_base", models.DecimalField(decimal_places=4, max_digits=7)),
                ("cobra_iva", models.BooleanField(default=False)),
                ("porcentaje_iva", models.DecimalField(decimal_places=2, default=decimal.Decimal("16.00"), max_digits=5)),
                ("fecha_referencia", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("canal_cobro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="esquemas_comision", to="ledger.canalcobro")),
            ],
            options={
                "verbose_name": "esquema de comisión",
                "verbose_name_plural": "esquemas de comisión",
                "ordering": ["canal_cobro__nombre", "nombre"],
            },
        ),
        migrations.RenameField(
            model_name="ingreso",
            old_name="monto",
            new_name="monto_bruto",
        ),
        migrations.AddField(
            model_name="ingreso",
            name="canal_cobro",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ingresos", to="ledger.canalcobro"),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="esquema_comision",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ingresos", to="ledger.esquemacomision"),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="porcentaje_comision_aplicado",
            field=models.DecimalField(decimal_places=4, default=decimal.Decimal("0.0000"), max_digits=7),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="comision",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="monto_neto",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="comision_manual",
            field=models.BooleanField(default=False),
        ),
    ]
