# Generated by Django 6.0.5 on 2026-06-04

from django.db import migrations, models


def copiar_canal_a_canales(apps, schema_editor):
    EsquemaComision = apps.get_model("ledger", "EsquemaComision")

    for esquema in EsquemaComision.objects.exclude(canal_cobro_id__isnull=True):
        esquema.canales_cobro.add(esquema.canal_cobro_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_backfill_monto_neto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="esquemacomision",
            options={
                "ordering": ["nombre"],
                "verbose_name": "esquema de comisión",
                "verbose_name_plural": "esquemas de comisión",
            },
        ),
        migrations.AddField(
            model_name="esquemacomision",
            name="canales_cobro",
            field=models.ManyToManyField(
                blank=True,
                related_name="esquemas_comision",
                to="ledger.canalcobro",
            ),
        ),
        migrations.RunPython(copiar_canal_a_canales, noop_reverse),
        migrations.RemoveField(
            model_name="esquemacomision",
            name="canal_cobro",
        ),
    ]
