# Generated by Django 6.0.5 on 2026-06-04 21:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_canal_predeterminado_ingreso_politica"),
    ]

    operations = [
        migrations.CreateModel(
            name="GastoMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "gasto de material",
                "verbose_name_plural": "gastos de material",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="conceptoingreso",
            name="incluye_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conceptoingreso",
            name="monto_material_sugerido",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="material_excedente",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="material_recuperado",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="monto_material_cobrado",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="pool_material_antes",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="pool_material_despues",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
