# Generated by Django 6.0.5 on 2026-06-11 19:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0009_catalogos_public_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "pendiente"),
                            ("cobrado", "cobrado"),
                            ("cancelado", "cancelado"),
                            ("abandonado", "abandonado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("nombre_referencia", models.CharField(blank=True, max_length=150)),
                ("notas", models.TextField(blank=True)),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "monto_material_cobrado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="ledger.origeningreso",
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket",
                "verbose_name_plural": "tickets",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TicketLinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=10
                    ),
                ),
                (
                    "monto_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "monto_material_cobrado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_lineas",
                        to="ledger.conceptoingreso",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="ledger.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de ticket",
                "verbose_name_plural": "líneas de ticket",
                "ordering": ["ticket", "orden", "id"],
            },
        ),
    ]
