# Generated by Django 6.0.5 on 2026-06-11 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0010_ticket_ticketlinea"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "canal_cobro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_pagos",
                        to="ledger.canalcobro",
                    ),
                ),
                (
                    "concepto_ingreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_pagos",
                        to="ledger.conceptoingreso",
                    ),
                ),
                (
                    "esquema_comision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_pagos",
                        to="ledger.esquemacomision",
                    ),
                ),
                (
                    "ingreso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_pago",
                        to="ledger.ingreso",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pago",
                        to="ledger.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago de ticket",
                "verbose_name_plural": "pagos de ticket",
                "ordering": ["-fecha", "-id"],
            },
        ),
    ]
