# Generated by Django 6.0.5 on 2026-06-12 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0012_operaciondispositivochremata"),
    ]

    operations = [
        migrations.AddField(
            model_name="operaciondispositivochremata",
            name="gasto_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operaciones_dispositivo",
                to="ledger.gastomaterial",
            ),
        ),
    ]
