# Generated by Django on 2026-06-02

from decimal import Decimal

from django.db import migrations, models


def backfill_monto_neto(apps, schema_editor):
    Ingreso = apps.get_model("chremata", "Ingreso")
    Ingreso.objects.all().update(
        comision=Decimal("0.00"),
        porcentaje_comision_aplicado=Decimal("0.0000"),
        monto_neto=models.F("monto_bruto"),
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("chremata", "0002_comisiones_canales_ingreso"),
    ]

    operations = [
        migrations.RunPython(backfill_monto_neto, noop_reverse),
    ]
