# Generated by Django on 2026-06-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chremata", "0004_alter_esquemacomision_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canalcobro",
            name="esquema_comision_predeterminado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="canales_predeterminados",
                to="chremata.esquemacomision",
            ),
        ),
        migrations.RemoveField(
            model_name="ingreso",
            name="metodo_pago",
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="canal_cobro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingresos",
                to="chremata.canalcobro",
            ),
        ),
    ]
