# Generated by Django 6.0.5 on 2026-06-11 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chremata", "0011_ticketpago"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperacionDispositivoChremata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("device_entry_id", models.CharField(max_length=100)),
                ("operation", models.CharField(max_length=50)),
                ("operation_contract", models.CharField(max_length=150)),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("processed", "processed"),
                            ("failed", "failed"),
                            ("conflict", "conflict"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("response", models.JSONField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
                ("recibido_en", models.DateTimeField(auto_now_add=True)),
                ("procesado_en", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "ingreso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operaciones_dispositivo",
                        to="chremata.ingreso",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operaciones_dispositivo",
                        to="chremata.ticket",
                    ),
                ),
                (
                    "ticket_pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operaciones_dispositivo",
                        to="chremata.ticketpago",
                    ),
                ),
            ],
            options={
                "verbose_name": "operación de dispositivo Chremata",
                "verbose_name_plural": "operaciones de dispositivo Chremata",
                "ordering": ["-recibido_en", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_id", "device_entry_id"),
                        name="uniq_chremata_operation_device_entry",
                    )
                ],
            },
        ),
    ]
