# Generated by Django 6.0.5 on 2026-06-17 19:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chremata", "0013_operaciondispositivochremata_gasto_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="CajaFisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "caja física",
                "verbose_name_plural": "cajas físicas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CajaSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("device_id", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[("abierta", "abierta"), ("cerrada", "cerrada")],
                        default="abierta",
                        max_length=20,
                    ),
                ),
                ("abierta_en", models.DateTimeField()),
                ("cerrada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "saldo_inicial_efectivo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "efectivo_contado_cierre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "efectivo_esperado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "diferencia_efectivo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_efectivo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_tarjeta",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_transferencia",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_bruto",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_material_cobrado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_comisiones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_neto_estimado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("resumen_snapshot", models.JSONField(blank=True, default=dict)),
                ("notas_apertura", models.TextField(blank=True)),
                ("notas_cierre", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "caja_fisica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones",
                        to="chremata.cajafisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "sesión de caja",
                "verbose_name_plural": "sesiones de caja",
                "ordering": ["-abierta_en"],
            },
        ),
    ]
