# Generated by Django 6.0.5 on 2026-06-17 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chremata", "0014_cajafisica_cajasesion"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastomaterial",
            name="caja_sesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gastos_material",
                to="chremata.cajasesion",
            ),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="caja_sesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingresos",
                to="chremata.cajasesion",
            ),
        ),
        migrations.AddField(
            model_name="operaciondispositivochremata",
            name="caja_sesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operaciones_dispositivo",
                to="chremata.cajasesion",
            ),
        ),
        migrations.AddField(
            model_name="ticketpago",
            name="caja_sesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="chremata.cajasesion",
            ),
        ),
    ]
