# Generated by Django 6.0.5 on 2026-06-18 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chremata", "0015_gastomaterial_caja_sesion_ingreso_caja_sesion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cajasesion",
            name="origen_ingreso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cajas_sesion",
                to="chremata.origeningreso",
                verbose_name="origen de ingreso por defecto",
            ),
        ),
    ]
